### ISSUE TITLE
status website disappeared after dist-upgrade

### ISSUE THREAD

**Issue by francisdb** [Ideetron/Lorank#14]
did the following

```
sudo apt-get update
sudo apt-get dist-upgrade
```

Now going to http://lorank8.local I get redirected to http://lorank8.local/bone101/Support/bone101/

tried `./Lorank/lorank8v1/upgrade` and saw the following

```
Could find a bonescript index.js file to patch, hope that's okay.
```

Now the bonescript service won't start because it can't find the globally installed bonescript npm package. What installs the bonescript npm package?

Any hints on how to fix this?

**Comment by devlaam** [comment]
Oops, updating the system software underneath the application software is a dangerous thing to do. Unfortunately I have no solution at hand, so i have to recreate this. Probably it is just something small that is broken, i think it undid a patch from the installation script. You could check the files that are normally patched, if there is an offender. Do not wipe and reinstall just like that, because most likely it will refuse because of a missing signature.

**Comment by francisdb** [comment]
Can you tell met what version of bonescript is installed on a standard device?

```
cat /usr/local/lib/node_modules/bonescript/package.json
```

**Comment by francisdb** [comment]
And what beaglebone image should I flash to start from scratch?

**Comment by devlaam** [comment]
We do not have one standard device installation, we always ship with the latest (shipped) image from beagleboard.org. We adapt our installation script to that version. The disadvantage is of course that we have many versions in the field. But this is an open source product, giving our users the possibility (and responsibility) to tweak it themselves. The version (in own Lorank) of package.json is:
```
root@lorank8:~# cat  /usr/local/lib/node_modules/bonescript/package.json | grep version
  "version": "0.2.4"
```

The version of the image itself can be seen at the dogtag, for example:
```
root@lorank8:~# cat /etc/dogtag 
BeagleBoard.org Debian Image 2015-03-01
```
If you calculate the md5 of that file, you can lookup if we support it:
```
root@lorank8:~# md5sum /etc/dogtag 
cb1efad0ea2c88604448eefce1b8aec7  /etc/dogtag
```
on [github:](https://github.com/Ideetron/Lorank/tree/master/lorank8v1), see the signature.
If it is supported, it should be possible to wipe your Lorank and reinstall it from github. Save your configuration files first! And it still is a risky procedure, and not recommended by Ideetron. (But updating the OS is also not recommended).

**Comment by francisdb** [comment]
Mine was on 2016-05-13
Reinstalled that version from the Beaglebone website
Checked out this repo
Ran install
Updated my local config

everything seems to be working fine now 👌
