### ISSUE TITLE
Support for 915MHz?

### ISSUE THREAD

**Issue by GillesC** [Ideetron/Lorank#15]
Hello

Do you provide 915MHz communication?
And if so, how can you configure the lorank to 915MHz.

Kind regards,
Gilles Callebaut

**Comment by barthiddink** [comment]
Yes we do.
You need a 915 MHz Lorank8 and a different global_cofn.json.
We can provide this.

Best regards,
Bart

**Comment by GillesC** [comment]
Hello

Can we use our existing lorank8 (868MHz)?

**Comment by barthiddink** [comment]
No, you need a new concentrator (915 MHz).

**Comment by GillesC** [comment]
Can we manually change the _concentrator_ at the _lorank8_ and modify the `global_cofn.json` to allow us to create a 915MHz-based gateway.

**Comment by barthiddink** [comment]
No, you need different hardware; IC980A ánd a different global_conf.json to drive the board.
Don't try and use the IC880A on 915 MHz. 
I will work on short range, but the on board filter will kill reception (>30dB attenuation) and almost no more downlink.
I'm even concerned the unit will be damaged when you try this.

You can buy a IC980A from us and we can send you a new json. This way you can modify the Lorank8 to a 915 MHz version.

**Comment by barthiddink** [comment]
You can buy a IC980A from us and we can send you a new json. This way you can modify the Lorank8.

**Comment by GillesC** [comment]
I have bought the IC980A from you (Belgium store).
Could you mail me the `global_cofn.json`? (gilles.callebaut@kuleuven.be)
