### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by abhatikar** [Ideetron/Lorank#18]
Hello,

I want to set up the gateway using a fresh BBG which is running the Debian 2018 release (f6942). I tried running the installation script, but it started complaining Lorank not found. 

Any documentation would be of great help.

Thanks in advance,

**Comment by barthiddink** [comment]
Did you modify the BBG?

**Comment by abhatikar** [comment]
Hello @barthiddink 
What modification you are referring to ? Could you please elaborate or point me to the documentation ?
thanks for your help.!

**Comment by abhatikar** [comment]
@barthiddink  provided the documentation of the hardware changes to the BBG
