### ISSUE TITLE
Manual source

### ISSUE THREAD

**Issue by francisdb** [Ideetron/Lorank#3]
Is the source file for the pdf available in github?
Would be nice to be able to send a patch for some typos.
And of course ideal to track changes...

**Comment by francisdb** [comment]
Preferably this would just be a markdown file

**Comment by devlaam** [comment]
The source of this file in LaTeX (which is plain ascii, perfect for git), i will add it on the next release.

**Comment by francisdb** [comment]
Euh, why is this closed?

**Comment by devlaam** [comment]
The manual source was pushed.

**Comment by francisdb** [comment]
Thanks!
