### ISSUE TITLE
Deploy / manage through resin.io / docker

### ISSUE THREAD

**Issue by francisdb** [Ideetron/Lorank#4]
In fact this is more of a question.

How hard would it be to set up a docker image like this:
https://github.com/rayozzie/ttn-resin-gateway-rpi-ic880a

Resin.io allows easy deployment of software remotely.
https://resin.io/how-it-works/

I might have a try to get this going if somebody can send me what you guys are doing to provision the device from scratch.

**Comment by devlaam** [comment]
Hi, this might be a nice idea. However, i am not sure i understand your question: "what you guys are doing to provision the device from scratch.". We do nothing special, we just hookup the Lorank and execute the install command as can be found in Lorank8v1. The one parameter you need to give it is the release version you would like to be installed, if none is provided it installs the latest, which may be untested.

**Comment by francisdb** [comment]
@devlaam thanks for the info, will probably not find the time in the near future to have a go at this
