### ISSUE TITLE
Please update poly_pkt_fwd to include log file

### ISSUE THREAD

**Issue by swiatecki** [Ideetron/Lorank#6]
Please update your version of poly_pkt_fwd to include this update

https://github.com/kersing/packet_forwarder/commit/13b2db5466e5aef7a513b856b740ed98af07f446

So logfile can be set with -l logfile

Thanks!

**Comment by devlaam** [comment]
Interesting extensions. For the Lorank they do not seem that urgent since most of our users do not use the service from the command line. For a broader use of the forwarder it may be convenient though. As soon as i have the time, i will have a further look into this.

**Comment by devlaam** [comment]
We decided not to allow options on the command line since this forwarder is mostly started as a service. Sorry about this.
