### ISSUE TITLE
Failing to start the concentrator

### ISSUE THREAD

**Issue by YannisDC** [Ideetron/Lorank#7]
I updated to 0.2.0 and now the concentrator fails all the time.
This is from the logs.

Sep 19 09:46:44 lorank8 lorank8v1[1974]: INFO: [main] Starting the concentrator
Sep 19 09:46:44 lorank8 lorank8v1[1974]: ERROR: [main] failed to start the concentrator
Sep 19 09:46:48 lorank8 systemd[1]: lorank.service holdoff time over, scheduling restart.
Sep 19 09:46:49 lorank8 systemd[1]: Unit lorank.service entered failed state.
Sep 19 09:46:49 lorank8 kernel: [  188.911215] gpio_request: gpio-14 (sysfs) status -16
Sep 19 09:46:49 lorank8 kernel: [  188.911261] export_store: status -16

How do I revert to an older install? Demo tomorrow

**Comment by devlaam** [comment]
The steps to take depend on the version you have, your linux skills and the actions you performed after the failure. 
From what version where you upgrading? 
Are you able to log into the device and do you know your way around on the command line? 
Did you perform any other actions then just the upgrade, for example, changes to the configuration files?
Did you perform the upgrade steps as written in the manual? Especially, did you made a backup copy of lorank8v1 directory? You only need to place that back and reboot. (The internal website may be  dysfunctional, but the forwarder itself should work as before)

**Comment by YannisDC** [comment]
I put my server (UDP listener) into the global and local config but that shouldn't have been the problem. Managed to do a total clean and reinstall now so it works. Sorry for the trouble

**Comment by devlaam** [comment]
Good to hear. Good luck with the demo tomorrow!
