### ISSUE TITLE
index.html not updated after upgrade to 0.2.1 (from 0.2.0)

### ISSUE THREAD

**Issue by sillevl** [Ideetron/Lorank#9]
Just did an upgrade to 0.2.1 (from 0.2.0) and everything worked well. The only thing that I notice is that the `index.html` page is not updated. The old version remains in `/var/lib/cloud9/`.

Skimming through the code, I find an update in the commit 548fb4b7464b3739662c923ccca75c6e7266edac that should solve the problem. This is added in the 0.2.1 version of the script. The problem might be that the old version of the script 0.2.0 is executed. The bug will remain for updates called on every version prior to 0.2.1. 

A solution might be to call the update script after the `git pull`.

I manually solved the issue by copying the new version of the `index.html` to `/var/lib/cloud9/`.

You can close this issue if you want, as the bug is probably already solved in the current version. This issue might be of value to users that upgrade from a version prior to 0.2.1.

**Comment by devlaam** [comment]
Thanks for your post. Yes, you are right, this is a design flaw, the old upgrade script that is typically on you system can only upgrade 'known' components.  The most 'easy' solution is to upgrade twice, and a more clean one is to do what is stated in the manual, as you point out correctly with a 'git pull' as follows:
   cd Lorank
   git checkout master
   git pull
   cd ..
   ./Lorank/lorank8v1/upgrade

**Comment by francisdb** [comment]
I had to restart the device for the statuspage to start working (could not load js after update)

Love the new status page / admin 👍

**Comment by devlaam** [comment]
Thx
